name: salt
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  flare_flutter: ^3.0.2
  flare_splash_screen: ^4.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_markdown: ^0.6.8
  flutter_secure_storage: ^4.2.1
  flutter_slidable: ^0.6.0
  flutter_stripe: ^2.0.1
  form_field_validator: ^1.1.0
  image_picker: ^0.8.4+3
  json_annotation: ^4.3.0
  provider: ^6.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - .env

  fonts:
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/sofia-pro-regular.otf
          weight: 400
        - asset: assets/fonts/sofia-pro-medium.otf
          weight: 500
        - asset: assets/fonts/sofia-pro-bold.otf
          weight: 700
        - asset: assets/fonts/sofia-pro-black.otf
          weight: 900
